# Default initial positions for ArmPlate's ros2_control fake system

initial_positions:
  AX_12A_04_1_Revolute_80: -1.8571
  AX_12A_04_2_Revolute_86: 1.5100
  AX_12A_04_3_Revolute_75: -0.2256
  AX_12A_04_4_Revolute_90: 0
  Nema_34_v3_Revolute_94: 0.5380
  STEPPER_MOTOR_Revolute_74: -1.5794
  firstDOF_final_Revolute_100: 0.6422
  gcomp1_Revolute_63: 0