# Default initial positions for ArmPlate's ros2_control fake system

initial_positions:
  AX_12A_04_1_Revolute_80: -1.037
  AX_12A_04_2_Revolute_86: -1.580
  AX_12A_04_3_Revolute_75: -0.323
  AX_12A_04_4_Revolute_90: 0
  Nema_34_v3_Revolute_94: 0.3730
  STEPPER_MOTOR_Revolute_74: -1.330
  firstDOF_final_Revolute_100: 0.662
  gcomp1_Revolute_63: 0