# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - firstDOF_final_Revolute_100
      - Nema_34_v3_Revolute_94
      - STEPPER_MOTOR_Revolute_74
      - AX_12A_04_3_Revolute_75
      - AX_12A_04_1_Revolute_80
      - AX_12A_04_2_Revolute_86
    action_ns: follow_joint_trajectory
  hand_controller:
    type: GripperCommand
    joints:
      - gcomp1_Revolute_63
      - AX_12A_04_4_Revolute_90
    action_ns: gripper_cmd