# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # mecanum_controller: 
    #   type: mecanum_drive_controller/MecanumDriveController

arm_controller:
  ros__parameters:
    joints:
      - firstDOF_final_Revolute_100
      - Nema_34_v3_Revolute_94
      - STEPPER_MOTOR_Revolute_74
      - AX_12A_04_3_Revolute_75
      - AX_12A_04_1_Revolute_80
      - AX_12A_04_2_Revolute_86
    action_ns: follow_joint_trajectory
    
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints: 
      - gcomp1_Revolute_63
      - AX_12A_04_4_Revolute_90
    action_ns: follow_joint_trajectory
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# mecanum_controller: 
  # ros__parameters: 
  #   front_left_wheel_command_joint_name: Wheel_motor_2_Revolute_105 
  #   rear_left_wheel_command_joint_name: Wheel_motor_3_Revolute_108 
  #   front_right_wheel_command_joint_name: Wheel_motor_1_Revolute_107 
  #   rear_right_wheel_command_joint_name: Wheel_motor_4_Revolute_106

  #   kinematics:
  #     base_frame_offset: { x: 1.0, y: 2.0, theta: 3.0 }
  #     wheels_radius: 0.75


  #   base_frame_id: base_footprint 
  #   odom_frame_id: odom 
  #   cmd_vel_timeout: 0.5 
  #   use_stamped_vel: false
  #   publish_rate: 50.0 
  #   enable_odom_tf: true