# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

arm_controller:
  ros__parameters:
    joints:
      - firstDOF_final_Revolute_100
      - Nema_34_v3_Revolute_94
      - STEPPER_MOTOR_Revolute_74
      - AX_12A_04_3_Revolute_75
      - AX_12A_04_1_Revolute_80
      - AX_12A_04_2_Revolute_86
    action_ns: follow_joint_trajectory
    
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints: 
      - gcomp1_Revolute_63
      - AX_12A_04_4_Revolute_90
    action_ns: follow_joint_trajectory
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["Wheel_motor_1_Revolute_107","Wheel_motor_4_Revolute_106"]
    right_wheel_names: ["Wheel_motor_2_Revolute_105","Wheel_motor_3_Revolute_108"]

    wheel_separation: 0.4     # distance between left and right wheels
    wheel_radius: 0.075        # wheel radius

    base_frame_id: base_footprint
    odom_frame_id: odom

    use_stamped_vel: false
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    enable_odom_tf: true
    publish_odom: true